name: AKS Upgrade

on:
  workflow_dispatch:
    types: aks-cluster-upgrade
    input:
      resource_group:
        description: 'AKS cluster resource group'
        required: true
      cluster_name:
        description: 'AKS cluster name'
        required: true
      kubernetes_version:
        description: 'Version to upgrade cluster to'
        required: true
    secrets:
      azure_credentials:
        required: true

jobs:
  upgrade-sandbox:
    uses: ms-us-rcg-app-innovation/aks-operational-excellence/.github/workflows/aks-upgrade-template.yml@main
    with:
      environment: Sandbox
      resource_group: ${{ inputs.resource_group }}
      cluster_name: ${{ inputs.cluster_name }}
      kubernetes_version: ${{ inputs.kubernetes_version}}
    secrets: inherit

  upgrade-development:
    uses: ms-us-rcg-app-innovation/aks-operational-excellence/.github/workflows/aks-upgrade-template.yml@main
    needs: upgrade-sandbox
    with:
      environment: Development
      resource_group: ${{ inputs.resource_group }}
      cluster_name: ${{ inputs.cluster_name }}
      kubernetes_version: ${{ inputs.kubernetes_version}}
    secrets: inherit
