name: AKS Cluster Upgrade Template

on:
  workflow_call:
    types: aks-cluster-upgrade
    input:
      environment:
        description: "Cluster environment"
        required: true
      resource_group:
        description: "AKS cluster resource group"
        required: true
      cluster_name:
        description: "AKS cluster name"
        required: true
      kubernetes_version:
        description: "Version to upgrade cluster to"
        required: true
    secrets:
      azure_credentials:
        required: true

jobs:
  upgrade-control-plane:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Azure login
        uses: azure/login@v1.4.3
        with:
          creds: ${{ secrets.az_creds }}

      - name: AKS control-plane upgrade
        uses: azure/cli@v1.0.6
        with:
          inlineScript: |
            az aks upgrade --resource-group ${{ inputs.resource_group }} 
                           --name ${{ inputs.cluste_name }} 
                           --kubernetes-version ${{ inputs.kubernetes_version}}
                           --control-plane-only
                           --yes

  upgrade-nodes:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    needs: upgrade-control-plane
    steps:
      - name: Azure login
        uses: azure/login@v1.4.3
        with:
          creds: ${{ secrets.az_creds }}

      - name: AKS control-plane upgrade
        uses: azure/cli@v1.0.6
        with:
          inlineScript: |
            az aks upgrade --resource-group ${{ inputs.resource-group }} 
                           --name ${{ inputs.cluster-name }} 
                           --kubernetes-version ${{ inputs.kubernetes-version}}
                           --upgrade-control-plane
                           --yes
