name: AKS Environment deployment

on:
  workflow_dispatch:
    
jobs:
  deploy-sandbox:
    name: Sandbox
    uses: ms-us-rcg-app-innovation/aks-operational-excellence/.github/workflows/tf-deploy-template.yml@main
    with:
      environment: Sandbox
      tf_var_file: 'environments/sandbox.tfvars'
      working_directory: 'terraform/aks'
    secrets: inherit
  
  deploy-development:
    name: Development
    uses:  ms-us-rcg-app-innovation/aks-operational-excellence/.github/workflows/tf-deploy-template.yml@main
    needs: deploy-sandbox
    with:      
      environment: Development
      tf_var_file: 'environments/development.tfvars'
      working_directory: 'terraform/aks'
    secrets: inherit


          